apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: knaval
type: Opaque
stringData:
  DATABASE_URI: "mongodb://root:example@mongo:27017/?authSource=admin"
  REDIS_PASSWORD: "someredispassword"
  