apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: knaval-project
  namespace: argocd
spec:
  description: "Proyecto ArgoCD para ExpensyApp"
  sourceRepos:
    - "*"
  destinations:
    - namespace: knaval
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"